datacontainer:
  image: ubuntu:14.04.3
  volumes:
    - /var/lib/postgresql/data
    - /usr/share/elasticsearch/data
    - /data
  command: "true"

postgres:
  image: postgres:9.4.5
  restart: always
  environment:
    POSTGRES_USER: pirozhki
    POSTGRES_PASSWORD: mysecretpassword
    PGDATA: /var/lib/postgresql/data
  command: postgres -c config_file=/var/lib/postgresql/postgresql.conf
  volumes_from:
    - datacontainer
  volumes:
    - ./config/postgresql.conf:/var/lib/postgresql/postgresql.conf

redis:
  image: redis:3.0.4
  restart: always
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes_from:
    - datacontainer
  volumes:
    - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro

elasticsearch:
  image: elasticsearch:2.1.1
  restart: always
  volumes_from:
    - datacontainer
  volumes:
    - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    - ./config/elasticsearch-logging.yml:/usr/share/elasticsearch/config/logging.yml:ro

logstash:
  image: logstash:2.1.1
  restart: always
  command: logstash -f /opt/logstash.conf
  links:
    - redis
    - elasticsearch
  volumes:
    - ./config/logstash.conf:/opt/logstash.conf:ro

kibana:
  image: kibana:4.3.1
  restart: always
  links:
    - elasticsearch
  environment:
    - CONFIG_PATH=/opt/kibana/config/kibana-pirozhki.yml
  volumes:
    - ./config/kibana.yml:/opt/kibana/config/kibana-pirozhki.yml:ro

sidekiqweb:
  image: zubkonst/pirozhki:0.5.3.1
  restart: always
  command: puma -C config/sidekiq_web.rb
  environment:
    APP_ENV: production
  links:
    - redis
  volumes:
    - ./variables:/pirozhki/config/variables:ro

worker:
  image: zubkonst/pirozhki:0.5.3.1
  restart: on-failure
  command: sidekiq -r ./app.rb -C config/variables/sidekiq.yml
  environment:
    APP_ENV: production
  links:
    - postgres
    - redis
  volumes:
    - ./variables:/pirozhki/config/variables:ro

nginx:
  image: nginx:1.9.7
  restart: always
  ports:
    - "80:80"
  links:
    - sidekiqweb
    - kibana
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
