common: &default_settings
  instagram:
    proxy:
    request_delay: 0
    client_id: REPLACE_ME
    client_secret: REPLACE_ME
  web:
    username: admin
    password:
    session_secret:
  export:
    type: stdout
  newrelic:
    enabled: true
  logging:
    type: stdout

test:
  <<: *default_settings
  newrelic:
    enabled: false

development:
  <<: *default_settings

production:
  <<: *default_settings
  web:
    username: admin
    password: admin
    session_secret: REPLACE_ME
  export:
    type: logstash_redis
    driver: :hiredis
    url: redis://redis:6379/1
  logging:
    type: file
